export default {
  districts: [
    { label: "Kavrepalanchok", value: "loc1" },
    { label: "Kaski", value: "loc2" },
    { label: "Chitwan", value: "loc3" },
    { label: "Dang", value: "loc4" },
    { label: "Bara", value: "loc5" },
    { label: "Bhaktapur", value: "loc6" },
    { label: "Lalitpur", value: "loc7" },
    { label: "Mustang", value: "loc8" },
    { label: "Manang", value: "loc9" },
    { label: "Palpa", value: "loc10" },
    { label: "Butwal", value: "loc11" },
    { label: "Mugu", value: "loc12" },
    { label: "Dolpa", value: "loct13" },
    { label: "Ilam", value: "loc14" },
    { label: "Parsa", value: "loc15" },
    { label: "Arghakhanchi", value: "loc16" },
    { label: "Bhojpur", value: "loc17" },
    { label: "Dhankuta", value: "loc18" },
    { label: "Jhapa", value: "loc19" },
    { label: "Khotang", value: "loc20" },
    { label: "Morang", value: "loc21" },
    { label: "Okhaldhunga", value: "loc22" },
    { label: "Panchthar", value: "loc23" },
    { label: "Sankhuwasabha", value: "loc24" },
    { label: "Sunsari", value: "loc25" },
    { label: "Taplejung", value: "loc26" },
    { label: "Tehrathum", value: "loc27" },
    { label: "Udayapur", value: "loc28" },
    { label: "Rautahat", value: "loc29" },
    { label: "Sarlahi", value: "loc30" },
    { label: "Dhanusha", value: "loc31" },
    { label: "Siraha", value: "loc32" },
    { label: "Mahottari", value: "loc33" },
    { label: "Saptari", value: "loc34" },
    { label: "Sindhuli", value: "loc35" },
    { label: "Ramechhap", value: "loc36" },
    { label: "Dolakha", value: "loc37" },
    { label: "Dhading", value: "loc38" },
    { label: "Nuwakot", value: "loc39" },
    { label: "Rasuwa", value: "loc40" },
    { label: "Sindhupalchok", value: "loc41" },
    { label: "Makwanpur", value: "loc42" },
    { label: "Baglung", value: "loc43" },
    { label: "Gorkha", value: "loc44" },
    { label: "Myagdi", value: "loc45" },
    { label: "Nawalpur", value: "loc46" },
    { label: "Parbat", value: "loc47" },
    { label: "Syangja", value: "loc48" },
    { label: "Tanahun", value: "loc49" },
    { label: "Kapilvastu", value: "loc50" },
    { label: "Parasi", value: "loc51" },
    { label: "Rupandehi", value: "loc52" },
    { label: "Gulmi", value: "loc53" },
    { label: "Dang", value: "loc54" },
    { label: "Pyuthan", value: "loc55" },
    { label: "Rolpa", value: "loc56" },
    { label: "Eastern Rukum", value: "loc57" },
    { label: "Banke", value: "loc58" },
    { label: "Bardiya", value: "loc59" },
    { label: "Salyan", value: "loc60" },
    { label: "Humla", value: "loc61" },
    { label: "Jumla", value: "loc62" },
    { label: "Kalikot", value: "loc63" },
    { label: "Surkhet", value: "loc64" },
    { label: "Dailekh", value: "loc65" },
    { label: "Jajarkot", value: "loc66" },
    { label: "Kailali", value: "loc67" },
    { label: "Achham", value: "loc68" },
    { label: "Doti", value: "loc69" },
    { label: "Bajhang", value: "loc70" },
    { label: "Bajura", value: "loc71" },
    { label: "Kanchanpur", value: "loc72" },
    { label: "Dadeldhura", value: "loc73" },
    { label: "Baitadi", value: "loc74" },
    { label: "Darchula", value: "loc75" },
  ],
  province: [
    { label: "Province No.1", value: "prov1" },
    { label: "Province No.2", value: "prov2" },

    { label: "Bagmati", value: "prov3" },
    { label: "Gandaki", value: "prov4" },
    { label: "Lumbini", value: "prov5" },
    { label: "Karnali", value: "prov6" },
    { label: "Sudurpashchim", value: "prov7" },
  ],
};
